### ISSUE TITLE
Add subprotocols helpers for Meta

### ISSUE THREAD

**Issue by egregors** [logux/django#28]
- [x] subprotocols support
- [x] add docs #20

**Comment by egregors** [comment]
@ai few questions:

Should I add `subprotocol` and `supports` server settings? Smth like:
```python
# settings.py
LOGUX_SUBPROTOCOL = '1.1.0'

LOGUX_SUBPROTOCOL_SUPPORTS = [
    LOGUX_SUBPROTOCOL,
    '1.0.0',
    '1.0.1',
    '1.0.2'
]
```

Should my `meta.subprotocol` helpers support `^` and `~` syntax? Semver spec does not contain a description of them. 

What server should do, if a request meta does not contain `subprotocol` key?

**Comment by ai** [comment]
> Should I add subprotocol and supports server settings?

We can specify `LOGUX_SUBPROTOCOL` and `LOGUX_SUBPROTOCOL_SUPPORTS` because of the current Logux Server architecture. We do not send this data to the back-end, because we have validation that the developer set `subprotocol` in the server’s code.

I added [the issue](https://github.com/logux/server/issues/90) but do not plan to do it this month.

> Should my meta.subprotocol helpers support ^ and ~ syntax?

We should support of syntaxes from [npm dependencies syntax](https://docs.npmjs.com/misc/semver). 

I think this package will provide this range syntax support https://pypi.org/project/semantic-version/

**Comment by egregors** [comment]
> I think this package will provide this range syntax support https://pypi.org/project/semantic-version/

As long as logux server does not send any subprotocol info through the proxy to the backend, I believe we do not need to add one more unnecessary dependency. For now, I added a way to get access to subprotocol info in the Meta, like:
```python
...
    def process(self, action: Action, meta: Optional[Meta]) -> None:
        if meta.subprotocol == '0.1.1':
            pass
        ...
```

I suggest extending meta utils only when proxy will starts sending subprotocol info to the backend.

**Comment by ai** [comment]
> As long as logux server does not send any subprotocol info through the proxy to the backend

Nope. Logux Server sends `meta` to back-end with `meta.subprotocol`.

I told you previously, that back-end does not need to set `subprotocol` or to refuse client’s connection based on `supports`. But back-end can still have different logic depends on client’s `subprotocol`.

**Comment by egregors** [comment]
So, let's give base `meta.subprotocol` support for now. And expand it when it will be really necessary.

If you agree, should we close it for now?

**Comment by ai** [comment]
👍
