### ISSUE TITLE
Streaming a responses to Logux

### ISSUE THREAD

**Issue by egregors** [logux/django#4]
Performance considerations

Django is designed for short-lived requests. Streaming responses will tie a worker process for the entire duration of the response. This may result in poor performance.

Generally speaking, you should perform expensive tasks outside of the request-response cycle, rather than resorting to a streamed response.

So, for this purpose, we should use `@async` from Django 3.+, or external queue service like Celery. 

Or we may just implement streaming with a disclaimer in Docs :3

I suggest for the first release implement just full responses without streaming.

**Comment by ai** [comment]
> Generally speaking, you should perform expensive tasks outside of the request-response cycle, rather than resorting to a streamed response.

Yeap, often the streaming response is used in some very long tasks. For instance, you ask the server to download 1 GB file over the network and process it with neural network. It could take 10 minutes. This is why they recommend using `async`.

In the case of Logux, I hope, most of `LoguxCommand` calls will be very quick: go to database, compare data, save data to the database. Of course, we will have multiple commands per each request, but I do not think it will be a big deal.

So I think, we do not need to work outside of the request-response cycle since we do not have long background tasks in Logux.

**Comment by egregors** [comment]
Streaming moved to the next after first release

**Comment by ai** [comment]
Should we keep it opeenned? We can use milestones to mark what is important for initial release and what we will do after.
