### ISSUE TITLE
django versions support?

### ISSUE THREAD

**Issue by sobolevn** [logux/django#47]
Currently CI specifies only `2.2` (current LTS) as a supported version.
What about `3.x` versions?

**Comment by egregors** [comment]
Originally, `django>=2.2,<3` was a requirement for the first version of this project. And that's why we process Actions synchronously, instead of writing into the streams for example. For full support `django>=3,<4` we should rewrite Actions processing to async way, I guess. 

However, I suppose the current implementation could work properly with Django 3. I'll gonna try to test it and add it to the CI pipeline. 

🐈

**Comment by egregors** [comment]
Looks like it just works 👌 👌 👌
